name: stonewooddesignlab
favicon: null
layout_spectrum: 0.42351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f8f3'
    - '#6f949c'
    - '#152a36'
    - '#2d5e72'
    - '#93b0b7'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
