name: stonewooddesignlab
favicon: null
layout_spectrum: 0.74912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06171b'
    - '#064a3d'
    - '#107d6d'
    - '#fefefe'
    - '#8ea8a5'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
