name: stonewooddesignlab
favicon: null
layout_spectrum: 0.42351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbe5ee'
    - '#c3d3db'
    - '#94a4ab'
    - '#6b858f'
    - '#57727c'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
