name: stonewooddesignlab
favicon: null
layout_spectrum: 0.42351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#011b16'
    - '#ccc0ab'
    - '#989a97'
    - '#617a59'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
